### ISSUE TITLE
Queuing bug

### ISSUE THREAD

**Issue by lus** [DRSchlaubi/mikbot#29] opened 2021-11-02 21:31 UTC
Sometimes when I try to queue a song the bot simply starts playing it while skipping the current playing one. I can't really say for sure why that happens as it does not seem like there are any error messages logged in that case.

**Comment by DRSchlaubi** [comment] 2021-11-03 16:24
The only way this should be possible is when the bot has no queue, and doesn't get the player update event from lava Link, which should only be the case if you queue two songs to quickly

**Comment by DRSchlaubi** [comment] 2022-01-31 16:32
Since I don't have additional information regarding this and couldn't reproduce it myself, I am going to close this

**Closed by DRSchlaubi** 2022-01-31 16:32 UTC
Labels: bug
